default: related.dvi

OUTPUT_FILES = \
   related.dvi related.pdf related.pdf related.txt

related.dvi related.pdf: \
	related.tex intro.tex \
	stackable.tex semantic.tex softupdates.tex journaling.tex \
	related.bib

include Makefile_tex_base
